name: Devops

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Save Service Account Key
        run: |
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > $HOME/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV

      - name: Deploy to Firebase (master)
        if: github.ref == 'refs/heads/master'
        run: firebase deploy --only hosting --project my-dev-ops-app

      - name: Deploy to Firebase (dev)
        if: github.ref == 'refs/heads/dev'
        run: firebase deploy --only hosting --project my-dev-ops-app
